[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lunax"
authors = [{name = "yangfa-zhang", email = "yangfa1027@gmail"}]
dynamic = ["version", "description"]
